name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository and persist credentials
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keeps the GitHub token active for pushing

      # Generate the snake GIF and SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SAMIUL-35
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show build status for easier debugging
      - run: git status

      # Commit and push the generated snake graphics to the 'output' branch
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Update snake contribution graph"
          git push origin output

      # Deploy the snake graphics to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
